<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // resolve,reject,all,race
      // resove == then ,reject == catch
      // let promise = new Promise((resolve, reject) => {
      //   reject(1111);
      // });
      // promise
      //   .then(res => {
      //     console.log("成功", res);
      //   })
      //   .catch(err => {
      //     console.log("失败", err);
      //   });

      function promise1(status) {
        return new Promise((resolve, reject) => {
          if (status) {
            resolve("第一个promise成功");
          } else {
            reject("第一个promise失败");
          }
        });
      }

      function promise2(status) {
        return new Promise((resolve, reject) => {
          if (status) {
            resolve("第2个promise成功");
          } else {
            reject("第2个promise失败");
          }
        });
      }

      function promise3(status) {
        return new Promise((resolve, reject) => {
          if (status) {
            resolve("第3个promise成功");
          } else {
            reject("第3个promise失败");
          }
        });
      }

      // promise1(true)
      //   .then(res => {
      //     console.log(res);
      //     return promise2(true);
      //   })
      //   .then(jre => {
      //     console.log(jre);
      //     return promise3(true);
      //   })
      //   .then(json => {
      //     console.log(json);
      //   })
      //   .catch(err => {});

      // 必须全为true，才能走then
      Promise.all([promise1(true), promise2(false), promise3(true)])
        .then(res => {
          console.log(res);
        })
        .catch(err => {
          console.log(err);
        });

      // 首个promise不为假，继续链式调用，直到有一个为true;首个为假，直接走catch
      Promise.race([promise1(false), promise2(true), promise3(false)])
        .then(res => {
          console.log(res);
        })
        .catch(err => {
          console.log(err);
        });
    </script>
  </body>
</html>
